services:
  frontend:
    container_name: frontend
    image: nginx:1.28
    restart: always
    networks:
      - main-network
    ports:
      - 80:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: backend
    image: uv:1
    restart: always
    ports:
      - 8000:8000
    networks:
      - main-network
    working_dir: /workspace
    volumes:
      - ./backend/main.py:/workspace/main.py
      - ./backend/settings.py:/workspace/settings.py
      - ./backend/pyproject.toml:/workspace/pyproject.toml
      - ./backend/uv.lock:/workspace/uv.lock
      - ./backend/.python-version:/workspace/.python-version
    environment:
      - HOST_IP=http://tv.weareithero.cloud
    command: [ "uv", "run", "fastapi", "run" ]

networks:
  main-network:
    driver: bridge
