name: Windows PC Job

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Install Modules
        working-directory: ./frontend
        run: npm install

      - name: Create .env 
        working-directory: ./frontend
        run: |
          "VITE_API_URL=${{ secrets.VITE_API_URL }}" | Set-Content -Path .env -Encoding UTF8
          "VITE_API_URL_MAIN=${{ secrets.VITE_API_URL_MAIN }}" | Add-Content -Path .env
          "VITE_API_URL_SKM=${{ secrets.VITE_API_URL_SKM }}" | Add-Content -Path .env
          "VITE_API_URL_HG=${{ secrets.VITE_API_URL_HG }}" | Add-Content -Path .env
          "VITE_API_URL_TV=${{ secrets.VITE_API_URL_TV }}" | Add-Content -Path .env
      - name: Node Build
        working-directory: ./frontend
        run: npm run build
      
      - name: Docker Down
        working-directory: .
        run: docker compose down
        continue-on-error: true

      - name: Docker Up
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
        working-directory: .
        run: docker compose up -d
