name: Windows PC Job

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .
      
      # - name: Docker Down
      #   working-directory: .
      #   run: docker compose down
      #   continue-on-error: true

      - name: Docker Up
        working-directory: .
        run: docker compose up -d
